apiVersion: v1
kind: Service
metadata:
  name: stemai-backend-svc
  namespace: stemai-tutor
  labels:
    app: stemai-backend
spec:
  type: ClusterIP
  selector:
    app: stemai-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
