apiVersion: v1
kind: Service
metadata:
  name: stemai-frontend-svc
  namespace: stemai-tutor
  labels:
    app: stemai-frontend
spec:
  type: ClusterIP
  selector:
    app: stemai-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
